config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root 'home#index'

  #intro routes
  get '/intro/intro', to: 'intro#intro'
  get '/intro/rules', to: 'intro#rules'
  get '/intro/history', to: 'intro#history'
  get '/intro/slogan', to: 'intro#slogan'
  get '/intro/partner', to: 'intro#partner'

  #matches routes
  resources :matches
  get '/match/table', to: 'matches#table'

  #boards & posts routes
  resources :posts
  resources :boards do
    resources :posts
  end
  resources :boards

  #volunteer routes
  resources :volunteers
  get '/volunteer/activity', to: 'volunteers#activity'
  get '/volunteer/volunteer_history', to: 'volunteers#volunteer_history'

  resources :members
  resources :tables

  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/volunteer.rb
class Volunteer < ApplicationRecord
  belongs_to :user

  def self.set_dummy_datas
    30.times do |i|
      Volunteer.create(
        title: "title_#{i}",
        content: "content_#{i}",
        user_id: 1
      )
    end
  end
end

app/controllers/volunteers_controller.rb
class VolunteersController < ApplicationController
  before_action :set_volunteer, only: %i[ show edit update destroy ]

  # GET /volunteers or /volunteers.json
  def index
    @volunteers = Volunteer.all.includes(:user)
    @volunteers = Volunteer.page(params[:page])
  end

  # GET /volunteers/1 or /volunteers/1.json
  def show
    @volunteer.increment!(:view_count)
  end

  # GET /volunteers/new
  def new
    @volunteer = Volunteer.new
  end

  # GET /volunteers/1/edit
  def edit
  end

  # POST /volunteers or /volunteers.json
  def create
    @volunteer = Volunteer.new(volunteer_params)
    @volunteer.user_id = current_user.id

    respond_to do |format|
      if @volunteer.save
        format.html { redirect_to @volunteer, notice: "Volunteer was successfully created." }
        format.json { render :show, status: :created, location: @volunteer }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @volunteer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /volunteers/1 or /volunteers/1.json
  def update
    @volunteer.user_id = current_user.id

    respond_to do |format|
      if @volunteer.update(volunteer_params)
        format.html { redirect_to @volunteer, notice: "Volunteer was successfully updated." }
        format.json { render :show, status: :ok, location: @volunteer }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @volunteer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /volunteers/1 or /volunteers/1.json
  def destroy
    @volunteer.destroy
    respond_to do |format|
      format.html { redirect_to volunteers_url, notice: "Volunteer was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def activity
  end

  def volunteer_history
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_volunteer
      @volunteer = Volunteer.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def volunteer_params
      params.require(:volunteer).permit(:title, :content, :view_count, :user_id)
    end
end

app/helpers/volunteers_helper.rb
module VolunteersHelper
end

app/views/volunteers/_form.html.erb
<div class="main-container">
  <%= form_with(model: volunteer, local: true) do |form| %>
    <% if volunteer.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(volunteer.errors.count, "error") %> prohibited this volunteer from being saved:</h2>

        <ul>
          <% volunteer.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= form.label :title %>
      <%= form.text_field :title %>
    </div>

    <div class="field">
      <%= form.label :content %>
      <%= form.text_area :content %>
    </div>

    <div class="actions">
      <%= form.submit %>
    </div>
  <% end %>

</div>

app/views/volunteers/_menu.html.erb
<div class="menu-bar">
  <div class="menu">
    <h1 class="menu-title">봉사</h1>
    <ul class="menu-list">
      <li><%= link_to '봉사소개', '/volunteer/activity', class: "menu-list-item" %></li>
      <li><%= link_to '역대활동', '/volunteer/volunteer_history', class: "menu-list-item" %></li>
      <li><%= link_to '자원봉사모집', '/volunteers', class: "menu-list-item" %></li>
    </ul>
  </div>
</div>

app/views/volunteers/activity.html.erb
<%= render 'menu' %>
<div class="main-container">
  <h4>IEMU11 봉사활동 소개</h4>

  <div class="intro">
    <div class="intro-img">
      이미지
    </div>
  </div>

  <div class="mid-line"></div>

  <div class="intro">
    <div class="intro-img">
      이미지
    </div>
  </div>
</div>

app/views/volunteers/edit.html.erb
<%= render 'menu' %>

<div class="main-container">
  <h1>Editing Volunteer</h1>

  <%= render 'form', volunteer: @volunteer %>

  <%= link_to 'Show', @volunteer %> |
  <%= link_to 'Back', volunteers_path %>
</div>

app/views/volunteers/index.html.erb
<%= render 'menu' %>

<div class="main-container">
  <h4>자원봉사 모집</h4>

  <table class="board-normal">
    <thead>
    <tr>
      <th>번호</th>
      <th>제목</th>
      <th>작성자</th>
      <th>조회수</th>
      <th>작성일</th>
    </tr>
    </thead>

    <tbody>
    <% @volunteers.order("created_at DESC").each do |volunteer| %>
      <tr>
        <td><%= volunteer.id %></td>
        <td><%= link_to volunteer.title, volunteer %></td>
        <td><%= volunteer.user.id %></td>
        <td><%= volunteer.view_count %></td>
        <td><%= volunteer.created_at.strftime("%Y.%m.%d") %></td>
      </tr>
    <% end %>
    </tbody>
  </table>

  <%= paginate @volunteers %>

  <br>
  <% if user_signed_in? %>
    <%= link_to '새 글쓰기', new_volunteer_path, class: 'new-btn' %>
  <%end %>

</div>

app/views/volunteers/new.html.erb
<%= render 'menu' %>
<div class="main-container">
  <h2>자원봉사 모집 작성페이지</h2>

  <%= render 'form', volunteer: @volunteer %>

  <%= link_to 'Back', volunteers_path %>
</div>

app/views/volunteers/show.html.erb
<%= render 'menu' %>

<div class="main-container">
  <h4>자원봉사 모집</h4>

  <h1 class="post-title">
    <%= @volunteer.title %>
  </h1>

  <span class="post-user-name"><%= @volunteer.user %></span>
  <span>
    <% if user_signed_in? %>
      <%= link_to '수정', edit_volunteer_path %> |
      <%= link_to '삭제', @volunteer, method: :delete, data: { confirm: '게시물을 삭제하시겠습니까?' }%>
    <%end %>
  </span>

  <div class="float-wrap">
    <p class="post-time-view"><%= @volunteer.created_at.strftime("%Y-%m-%d") %> , 조회수 <%= @volunteer.view_count.to_i %></p>
    <p class="post-list"><%= link_to '목록', volunteers_path %></p>
  </div>

  <div class="post-mid-line"></div>

  <p class="post-content">
    <%= @volunteer.content %>
  </p>

</div>

app/views/volunteers/volunteer_history.html.erb
<%= render 'menu' %>

<div class="main-container">
  <h4>역대활동</h4>

  <div class="intro">
    <div class="intro-img">
      이미지
    </div>
  </div>

  <div class="mid-line"></div>

  <div class="intro">
    <div class="intro-img">
      이미지
    </div>
  </div>
</div>