config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root 'home#index'

  #intro routes
  get '/intro/intro', to: 'intro#intro'
  get '/intro/rules', to: 'intro#rules'
  get '/intro/history', to: 'intro#history'
  get '/intro/slogan', to: 'intro#slogan'
  get '/intro/partner', to: 'intro#partner'

  #matches routes
  resources :matches
  get '/match/table', to: 'matches#table'

  #boards & posts routes
  resources :posts
  resources :boards do
    resources :posts
  end
  resources :boards

  #volunteer routes
  resources :volunteers
  get '/volunteer/activity', to: 'volunteers#activity'
  get '/volunteer/volunteer_history', to: 'volunteers#volunteer_history'

  resources :members
  resources :tables

  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/board.rb
class Board < ApplicationRecord
  belongs_to :user
  has_many :posts
end

app/models/match.rb
class Match < ApplicationRecord
  belongs_to :user

  mount_uploader :avatar, AvatarUploader
  require 'carrierwave/orm/activerecord'
end

app/models/member.rb
class Member < ApplicationRecord
  belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :board

  has_rich_text :content

  def self.set_dummy_datas
    30.times do |i|
      Post.create(
        title: "title_#{i}",
        content: "content_#{i}",
        board_id: [1, 7, 8].sample,
        user_id: 1
      )
    end
  end
end

app/models/table.rb
class Table < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :boards
  has_many :posts
  has_many :matches
  has_many :members
  has_many :tables
  has_many :volunteers
end

app/models/volunteer.rb
class Volunteer < ApplicationRecord
  belongs_to :user

  def self.set_dummy_datas
    30.times do |i|
      Volunteer.create(
        title: "title_#{i}",
        content: "content_#{i}",
        user_id: 1
      )
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    @post = Post.last

    @volunteer = Volunteer.last
  end
end

app/controllers/intro_controller.rb
class IntroController < ApplicationController
  def intro
  end

  def rules
  end

  # def history
  # end

  def slogan
  end

  def partner
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]
  before_action :set_board

  # GET /posts or /posts.json
  def index
    @posts = @board.present? ? @board.posts.all : Post.all
    @posts = Post.with_rich_text_content_and_embeds
  end

  # GET /posts/1 or /posts/1.json
  def show
    @post = Post.find(params[:id])
    @post.increment!(:view_count)
  end

  # GET /posts/new
  def new
    @post = @board.present? ? @board.posts.new : Post.new
  end

  # GET /posts/1/edit
  def edit
    @post = Post.find(params[:id])
  end

  # POST /posts or /posts.json
  def create
    @post = @post = @board.present? ? @board.posts.new(post_params) : Post.new(post_params)
    @post.user_id = current_user.id
    @post.user_name = current_user.user_name

    respond_to do |format|
      if @post.save
        format.html { redirect_to (@board.present? ? [@post.board, @post] : @post), notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    @post = Post.find(params[:id])

    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to (@board.present? ? [@post.board, @post] : @post), notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post = Post.find(params[:id])

    @post.destroy
    respond_to do |format|
      format.html {
        redirect_to board_path(@board), notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_post
    if @board.present?
      @post = @board.posts.find(params[:id])
    end
  end

  def set_board
    @board = Board.find(params[:board_id]) if params[:board_id].present?
  end

  # Only allow a list of trusted parameters through.
  def post_params
    params.require(:post).permit(:title, :content, :board_id, :user_id, :view_count, :user_name)
  end
end

app/controllers/tables_controller.rb
class TablesController < ApplicationController
  before_action :set_table, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, only: [:show, :create, :destroy, :new, :edit, :update]

  # GET /tables or /tables.json
  def index
    @tables = Table.all
    @table = Table.last
  end

  # GET /tables/1 or /tables/1.json
  def show
  end

  # GET /tables/new
  def new
    @table = Table.new
  end

  # GET /tables/1/edit
  def edit
  end

  # POST /tables or /tables.json
  def create
    @table = Table.new(table_params)
    @table.user_id = current_user.id

    respond_to do |format|
      if @table.save
        format.html { redirect_to @table, notice: "Table was successfully created." }
        format.json { render :show, status: :created, location: @table }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @table.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tables/1 or /tables/1.json
  def update
    @table.user_id = current_user.id

    respond_to do |format|
      if @table.update(table_params)
        format.html { redirect_to @table, notice: "Table was successfully updated." }
        format.json { render :show, status: :ok, location: @table }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @table.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tables/1 or /tables/1.json
  def destroy
    @table.destroy
    respond_to do |format|
      format.html { redirect_to tables_url, notice: "Table was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_table
      @table = Table.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def table_params
      params.require(:table).permit(:rank, :team_name, :match_count, :point, :win_count, :draw_count, :lose_count, :score_count, :lost_count, :recent_form, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/intro_helper.rb
module IntroHelper
end

app/helpers/matches_helper.rb
module MatchesHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/tables_helper.rb
module TablesHelper
end

app/helpers/volunteers_helper.rb
module VolunteersHelper
end

app/views/tables/_form.html.erb
<%= form_with(model: table, local: true) do |form| %>
  <% if table.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(table.errors.count, "error") %> prohibited this table from being saved:</h2>

      <ul>
        <% table.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :'순위' %>
    <%= form.number_field :rank %>
  </div>

  <div class="field">
    <%= form.label :'팀명' %>
    <%= form.text_field :team_name %>
  </div>

  <div class="field">
    <%= form.label :'경기수' %>
    <%= form.number_field :match_count %>
  </div>

  <div class="field">
    <%= form.label :'승점' %>
    <%= form.number_field :point %>
  </div>

  <div class="field">
    <%= form.label :'승리 수' %>
    <%= form.number_field :win_count %>
  </div>

  <div class="field">
    <%= form.label :'무승부 수' %>
    <%= form.number_field :draw_count %>
  </div>

  <div class="field">
    <%= form.label :'패배 수' %>
    <%= form.number_field :lose_count %>
  </div>

  <div class="field">
    <%= form.label :'득점 수' %>
    <%= form.number_field :score_count %>
  </div>

  <div class="field">
    <%= form.label :'실점 수' %>
    <%= form.number_field :lost_count %>
  </div>

  <div class="field">
    <%= form.label :'최근 5경기 결과' %>
    <%= form.text_field :recent_form %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/tables/_menu.html.erb
<div class="menu-bar">
  <div class="menu">
    <h1 class="menu-title">경기</h1>
    <ul class="menu-list">
      <li><%= link_to '일정 및 결과', matches_path, class: "menu-list-item" %></li>
      <li><%= link_to '순위', tables_path, class: "menu-list-item" %></li>
    </ul>
  </div>
</div>

app/views/tables/edit.html.erb
<%= render 'menu' %>

<div class="main-container">
  <h1>Editing Table</h1>

  <%= render 'form', table: @table %>

  <%= link_to 'Show', @table %> |
  <%= link_to 'Back', tables_path %>
</div>

app/views/tables/index.html.erb
<%=render 'menu' %>

<div class="main-container">
  <div class="league">
    <img class="k7-logo" src="<%=asset_path 'k7_logo.png' %>" alt="">
    <h4 class="league-txt">K7 서초권역리그</h4>
  </div>


  <table class="rank">
    <thead>
    <tr>
      <th>순위</th>
      <th>팀명</th>
      <th>경기수</th>
      <th>승점</th>
      <th>승</th>
      <th>무</th>
      <th>패</th>
      <th>득점</th>
      <th>실점</th>
      <th>최근 5경기</th>
    </tr>
    </thead>

    <tbody>
    <% @tables.each do |table| %>
      <tr>
        <td><%= link_to table.rank, table, class: "table-show" %></td>
        <td><span class="team-name"><%= table.team_name %></span></td>
        <td><%= table.match_count %></td>
        <td><%= table.point %></td>
        <td><%= table.win_count %></td>
        <td><%= table.draw_count %></td>
        <td><%= table.lose_count %></td>
        <td><%= table.score_count %></td>
        <td><%= table.lost_count %></td>
        <td><%= table.recent_form %></td>
      </tr>
    <% end %>
    </tbody>
  </table>

  <br>
  <% if user_signed_in? %>
    <%= link_to '순위표 업데이트', new_table_path, class: 'new-btn' %>
  <% end %>

  <div class="table-update">
    업데이트 날짜:  <%= @table.updated_at.strftime("%Y.%m.%d") %>
  </div>



</div>

app/views/tables/new.html.erb
<%= render 'menu' %>

<div class="main-container">
  <h1>New Table</h1>

  <%= render 'form', table: @table %>

  <%= link_to 'Back', tables_path %>
</div>

app/views/tables/show.html.erb
<%= render 'menu' %>

<div class="main-container">
  <p>
    <strong>Rank:</strong>
    <%= @table.rank %>
  </p>

  <p>
    <strong>Team name:</strong>
    <%= @table.team_name %>
  </p>

  <p>
    <strong>Match count:</strong>
    <%= @table.match_count %>
  </p>

  <p>
    <strong>Point:</strong>
    <%= @table.point %>
  </p>

  <p>
    <strong>Win count:</strong>
    <%= @table.win_count %>
  </p>

  <p>
    <strong>Draw count:</strong>
    <%= @table.draw_count %>
  </p>

  <p>
    <strong>Lose count:</strong>
    <%= @table.lose_count %>
  </p>

  <p>
    <strong>Score count:</strong>
    <%= @table.score_count %>
  </p>

  <p>
    <strong>Lost count:</strong>
    <%= @table.lost_count %>
  </p>

  <p>
    <strong>Recent form:</strong>
    <%= @table.recent_form %>
  </p>

  <%= link_to 'Edit', edit_table_path(@table) %>
  <%= link_to 'Destroy', @table, method: :delete, data: { confirm: 'Are you sure?' } %> |
  <%= link_to 'Back', tables_path %>

</div>