config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root 'home#index'

  #intro routes
  get '/intro/intro', to: 'intro#intro'
  get '/intro/rules', to: 'intro#rules'
  get '/intro/history', to: 'intro#history'
  get '/intro/slogan', to: 'intro#slogan'
  get '/intro/partner', to: 'intro#partner'

  #matches routes
  resources :matches
  get '/match/table', to: 'matches#table'

  #boards & posts routes
  resources :posts
  resources :boards do
    resources :posts
  end
  resources :boards

  #volunteer routes
  resources :volunteers
  get '/volunteer/activity', to: 'volunteers#activity'
  get '/volunteer/volunteer_history', to: 'volunteers#volunteer_history'

  resources :members
  resources :tables

  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/match.rb
class Match < ApplicationRecord
  belongs_to :user

  mount_uploader :avatar, AvatarUploader
  require 'carrierwave/orm/activerecord'
end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController
  before_action :set_match, only: %i[ show edit update destroy ]

  # GET /matches or /matches.json
  def index
    @matches = Match.all
  end

  # GET /matches/1 or /matches/1.json
  def show
  end

  # GET /matches/new
  def new
    @match = Match.new
  end

  # GET /matches/1/edit
  def edit
  end

  # POST /matches or /matches.json
  def create
    @match = Match.new(match_params)

    respond_to do |format|
      if @match.save
        format.html { redirect_to @match, notice: "Match was successfully created." }
        format.json { render :show, status: :created, location: @match }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @match.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /matches/1 or /matches/1.json
  def update
    respond_to do |format|
      if @match.update(match_params)
        format.html { redirect_to @match, notice: "Match was successfully updated." }
        format.json { render :show, status: :ok, location: @match }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @match.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /matches/1 or /matches/1.json
  def destroy
    @match.destroy
    respond_to do |format|
      format.html { redirect_to matches_url, notice: "Match was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def table
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_match
      @match = Match.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def match_params
      params.require(:match).permit(:title, :content, :time, :place, :score, :opponent, :user_id, :avatar)
    end
end

app/helpers/matches_helper.rb
module MatchesHelper
end

app/views/matches/_form.html.erb
<div class="main-container">
  <%= form_with(model: match, local: true) do |form| %>
    <% if match.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(match.errors.count, "error") %> prohibited this match from being saved:</h2>

        <ul>
          <% match.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= form.label :title %>
      <%= form.text_field :title %>
    </div>

    <div class="field">
      <%= form.label :content %>
      <%= form.text_area :content %>
    </div>

    <div class="field">
      <%= form.label :time %>
      <%= form.text_field :time %>
    </div>

    <div class="field">
      <%= form.label :place %>
      <%= form.text_field :place %>
    </div>

    <div class="field">
      <%= form.label :score %>
      <%= form.text_field :score %>
    </div>

    <div class="field">
      <%= form.label :opponent %>
      <%= form.text_field :opponent %>
    </div>

    <div class="field">
      <%= form.label :avatar %>
      <%= form.file_field :avatar %>
    </div>

    <div class="field">
      <%= form.label :user_id %>
      <%= form.text_field :user_id %>
    </div>

    <div class="actions">
      <%= form.submit %>
    </div>
  <% end %>

</div>

app/views/matches/_menu.html.erb
<div class="menu-bar">
  <div class="menu">
    <h1 class="menu-title">경기</h1>
    <ul class="menu-list">
      <li><%= link_to '일정 및 결과', matches_path, class: "menu-list-item" %></li>
      <li><%= link_to '순위', tables_path, class: "menu-list-item" %></li>
    </ul>
  </div>
</div>

app/views/matches/edit.html.erb
<%=render 'menu' %>

<div class="main-container">
  <h1>경기 결과 및 일정 수정</h1>

  <%= render 'form', match: @match %>

  <%= link_to 'Show', @match %> |
  <%= link_to '뒤로가기', matches_path %>
</div>

app/views/matches/index.html.erb
<%= render 'menu' %>

<div class="main-container">

  <h4>일정 및 결과</h4>

    <% @matches.order("created_at DESC").each do |match| %>
      <div class="m-s-box">
        <div class="m-s-01">
          <div class="m-title"><%= match.title %></div>
        </div>
        <div class="m-s-02">
          <div class="m-time"><%= match.time %></div>
          <div class="m-place"><%= match.place %></div>
        </div>
        <div class="m-s-03">
          <ul>
            <li class="m-name">IEMU11</li>
            <li class="emb"><img class="m-logo-iemu11" src="<%= asset_path 'logo.png' %>" alt=""></li>
            <li class="score"><p><%= match.score %></p></li>
            <li class="emb"><img class="m-logo" src="<%= match.avatar %>" alt=""></li>
            <li class="m-name"><%= match.opponent %></li>
          </ul>
        </div>
        <div class="m-s-04">
          <a href="https://cafe.naver.com/iemu11?iframe_url=/ArticleList.nhn%3Fsearch.clubid=29862873%26search.menuid=70%26search.boardtype=L" target="_blank" rel="noopener">
            <span>경기리뷰</span>
          </a>
        </div>
      </div>

      <% if user_signed_in? %>
        <%= link_to 'Show', match %>
        <%= link_to 'Edit', edit_match_path(match) %>
        <%= link_to 'Destroy', match, method: :delete, data: { confirm: 'Are you sure?' } %>
      <% end %>

    <% end %>


  <br>
  <div class="float-wrap">
    <% if user_signed_in? %>
      <%= link_to 'New Match', new_match_path, class: "new-btn" %>
    <% end %>
  </div>

</div>

app/views/matches/new.html.erb
<%= render 'menu' %>

<div class="main-container">
  <h1>경기 일정 및 결과 작성</h1>

  <%= render 'form', match: @match %>

  <%= link_to 'Back', matches_path %>
</div>

app/views/matches/show.html.erb
<%= render 'menu' %>

<div class="main-container">
  <p>
    <strong>Title:</strong>
    <%= @match.title %>
  </p>

  <p>
    <strong>Content:</strong>
    <%= @match.content %>
  </p>

  <p>
    <strong>Time:</strong>
    <%= @match.time %>
  </p>

  <p>
    <strong>Place:</strong>
    <%= @match.place %>
  </p>

  <p>
    <strong>Score:</strong>
    <%= @match.score %>
  </p>

  <p>
    <strong>Opponent:</strong>
    <%= @match.opponent %>
  </p>

  <p>
    <strong>User:</strong>
    <%= @match.user_id %>
  </p>

  <%= link_to 'Edit', edit_match_path(@match) %> |
  <%= link_to 'Back', matches_path %>

</div>

app/views/matches/table.html.erb
<%= render 'menu' %>

<div class="main-container">
  <div class="intro">
    <h2>순위</h2>
    <div class="intro-img">
      이미지
    </div>
  </div>

  <div class="mid-line"></div>
</div>