config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root 'home#index'

  #intro routes
  get '/intro/intro', to: 'intro#intro'
  get '/intro/rules', to: 'intro#rules'
  get '/intro/history', to: 'intro#history'
  get '/intro/slogan', to: 'intro#slogan'
  get '/intro/partner', to: 'intro#partner'

  #matches routes
  resources :matches
  get '/match/table', to: 'matches#table'

  #boards & posts routes
  resources :posts
  resources :boards do
    resources :posts
  end
  resources :boards

  #volunteer routes
  resources :volunteers
  get '/volunteer/activity', to: 'volunteers#activity'
  get '/volunteer/volunteer_history', to: 'volunteers#volunteer_history'

  resources :members
  resources :tables

  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :board

  has_rich_text :content

  def self.set_dummy_datas
    30.times do |i|
      Post.create(
        title: "title_#{i}",
        content: "content_#{i}",
        board_id: [1, 7, 8].sample,
        user_id: 1
      )
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]
  before_action :set_board

  # GET /posts or /posts.json
  def index
    @posts = @board.present? ? @board.posts.all : Post.all
    @posts = Post.with_rich_text_content_and_embeds
  end

  # GET /posts/1 or /posts/1.json
  def show
    @post = Post.find(params[:id])
    @post.increment!(:view_count)
  end

  # GET /posts/new
  def new
    @post = @board.present? ? @board.posts.new : Post.new
  end

  # GET /posts/1/edit
  def edit
    @post = Post.find(params[:id])
  end

  # POST /posts or /posts.json
  def create
    @post = @post = @board.present? ? @board.posts.new(post_params) : Post.new(post_params)
    @post.user_id = current_user.id
    @post.user_name = current_user.user_name

    respond_to do |format|
      if @post.save
        format.html { redirect_to (@board.present? ? [@post.board, @post] : @post), notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    @post = Post.find(params[:id])

    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to (@board.present? ? [@post.board, @post] : @post), notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post = Post.find(params[:id])

    @post.destroy
    respond_to do |format|
      format.html {
        redirect_to board_path(@board), notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_post
    if @board.present?
      @post = @board.posts.find(params[:id])
    end
  end

  def set_board
    @board = Board.find(params[:board_id]) if params[:board_id].present?
  end

  # Only allow a list of trusted parameters through.
  def post_params
    params.require(:post).permit(:title, :content, :board_id, :user_id, :view_count, :user_name)
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<div class="main-container">
  <%= form_with(model: @board.present? ? [@post.board, @post] : @post, local: true) do |form| %>

    <% if @post.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>
        <ul>
          <% @post.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= form.label :board_title, '카테고리' %>
      <%= form.collection_select :board_title, Board.all, :id, :title, prompt: true %>
    </div>

    <div class="field">
      <%= form.label :title, '제목'%>
      <%= form.text_field :title %>
    </div>

    <div class="field">
      <%= form.label :content, '내용' %>
      <%= form.rich_text_area :content %>
    </div>

<!--    <div class="field">-->
      <%#= form.label :view_count, '조회수' %>
      <%#= form.number_field :view_count %>
<!--    </div>-->

    <div class="actions">
      <%= form.submit '작성' %>
    </div>
  <% end %>
</div>

app/views/posts/_menu.html.erb
<div class="menu-bar">
  <div class="menu">
    <h1 class="menu-title">소식</h1>
    <ul class="menu-list">
      <li><%= link_to '공지사항', '/boards/1', class: "menu-list-item" %></li>
      <li><%= link_to '이벤트', '/boards/7', class: "menu-list-item" %></li>
      <li><%= link_to '언론보도', '/boards/8', class: "menu-list-item" %></li>
    </ul>
  </div>
</div>

app/views/posts/edit.html.erb
<%= render 'menu' %>

<div class="main-container">
  <h1>Editing Post</h1>

  <%= render 'form', post: @post %>

  <%= link_to 'Show', @post %> |
  <%= link_to 'Back', @post %>
</div>

app/views/posts/index.html.erb
<%= render 'menu' %>

<div class="main-container">

  <h2>게시물</h2>
  <table class="post-normal">
    <thead>
      <tr>
        <th>제목</th>
        <th>내용</th>
        <th>조회수</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @posts.each do |post| %>
        <tr class="table-news">
          <td><%= post.title %></td>
          <td><%= post.content %></td>
          <td><%= post.view_count %></td>
          <td><%= link_to '열기', (@board.present? ? [post.board, post] : post) %></td>
          <td><%= link_to '수정', (@board.present? ? edit_board_post_path(post.board, post) : edit_post_path(post)) %></td>
          <td><%= link_to '삭제', (@board.present? ? [post.board, post] : post), method: :delete, data: { confirm: 'Are you sure post?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <%#= paginate @posts %>
  <br>

  <div class="float-wrap">
  <%= link_to '새 글 쓰기', (@board.present? ?  new_board_post_path(@board) : new_post_path), class: "new-btn" %>
  </div>
</div>

app/views/posts/new.html.erb
<%= render 'menu' %>

<div class="main-container">
  <h1>새 글 작성</h1>

  <%= render 'form', post: @post %>

  <%= link_to '뒤로가기', :back %>
</div>

app/views/posts/show.html.erb
<%= render 'menu' %>

<div class="main-container">
  <h4><%= @post.board.title %></h4>

  <h1 class="post-title">
    <%= @post.title %>
  </h1>

  <span class="post-user-name"><%= @post.user_name %></span>
  <span>
    <% if user_signed_in? %>
      <%= link_to '수정', (@board.present? ? edit_board_post_path(@board)  : edit_post_path(@post)) %> |
      <%= link_to '삭제', (@board.present? ? [@post.board, @post] : @post), method: :delete, data: { confirm: '게시물을 삭제하시겠습니까?' }%>
    <% end %>
  </span>

  <div class="float-wrap">
    <p class="post-time-view"><%= @post.created_at.strftime("%Y-%m-%d") %> , 조회수 <%= @post.view_count.to_i %></p>
    <%= link_to '목록', board_path(@post.board), class: "post-list" %>
  </div>

  <div class="post-mid-line"></div>

  <p class="post-content">
    <%= @post.content %>
  </p>

  <hr class="post-content-line">
</div>